default_install_hook_types:
  - post-checkout
  - post-merge
  - post-rewrite
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: f0ba432faf5fcf51f38782f7b3be70fab53f1edd
    hooks:
      - id: uv-sync
