default_install_hook_types:
  - post-checkout
  - post-merge
  - post-rewrite
  - commit-msg
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: f0ba432faf5fcf51f38782f7b3be70fab53f1edd
    hooks:
      - id: uv-sync
  - repo: https://github.com/opensource-nepal/commitlint
    rev: 7d5177478584fa182b04a4a64d1b1b257b474cd2
    hooks:
      - id: commitlint